### ISSUE TITLE
yarn start的时候出现这个错误怎么解决？

### ISSUE THREAD

**Issue by Yhxiao98** [simbawus/blog#17]
ERROR in multi (webpack)-dev-server/client?http://0.0.0.0:8097 webpack/hot/dev-server Chrome
Module not found: Error: Can't resolve 'Chrome' in 'C:\Program Files\Git\blog'
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8097 webpack/hot/dev-server Chrome

**Comment by simbawus** [comment]
mac下打开chrome配置跟windows不一样，参考[这个链接](https://webpack.js.org/configuration/dev-server/#devserveropen)改下`config/webpack/webpack.dev.config.js`中devServer的配置

**Comment by Yhxiao98** [comment]
[image: image.png]您好！现在还有这几个问题能麻烦您替我瞧瞧吗？

simbawu <notifications@github.com> 于2019年10月28日周一 下午2:39写道：

**Comment by Yhxiao98** [comment]
[image: image.png]改了端口后显示的问题是这样的

simbawu <notifications@github.com> 于2019年10月28日周一 下午2:39写道：

**Comment by simbawus** [comment]
你图没传上来

**Comment by Yhxiao98** [comment]
[image: image.png]我发现还可以用这个方法，您的密码是？

simbawu <notifications@github.com> 于2019年10月28日周一 下午4:32写道：
